# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 502)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_mode = QtWidgets.QLabel(self.centralwidget)
        self.label_mode.setObjectName("label_mode")
        self.horizontalLayout.addWidget(self.label_mode)
        self.mode_selection_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.mode_selection_comboBox.setObjectName("mode_selection_comboBox")
        self.mode_selection_comboBox.addItem("")
        self.mode_selection_comboBox.addItem("")
        self.mode_selection_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.mode_selection_comboBox)
        self.label_load_path = QtWidgets.QLabel(self.centralwidget)
        self.label_load_path.setObjectName("label_load_path")
        self.horizontalLayout.addWidget(self.label_load_path)
        self.load_path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.load_path_lineEdit.setObjectName("load_path_lineEdit")
        self.horizontalLayout.addWidget(self.load_path_lineEdit)
        self.load_path_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_path_pushButton.setObjectName("load_path_pushButton")
        self.horizontalLayout.addWidget(self.load_path_pushButton)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.replacement_result_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replacement_result_groupbox.sizePolicy().hasHeightForWidth())
        self.replacement_result_groupbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.replacement_result_groupbox.setFont(font)
        self.replacement_result_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.replacement_result_groupbox.setObjectName("replacement_result_groupbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.replacement_result_groupbox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.detection_result_label = QtWidgets.QLabel(self.replacement_result_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detection_result_label.sizePolicy().hasHeightForWidth())
        self.detection_result_label.setSizePolicy(sizePolicy)
        self.detection_result_label.setMinimumSize(QtCore.QSize(400, 240))
        self.detection_result_label.setText("")
        self.detection_result_label.setScaledContents(True)
        self.detection_result_label.setObjectName("detection_result_label")
        self.verticalLayout_7.addWidget(self.detection_result_label)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.replacement_result_groupbox, 3, 1, 1, 1)
        self.original_source_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.original_source_groupbox.setFont(font)
        self.original_source_groupbox.setObjectName("original_source_groupbox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.original_source_groupbox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.original_source_label = QtWidgets.QLabel(self.original_source_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_source_label.sizePolicy().hasHeightForWidth())
        self.original_source_label.setSizePolicy(sizePolicy)
        self.original_source_label.setMinimumSize(QtCore.QSize(400, 240))
        self.original_source_label.setText("")
        self.original_source_label.setScaledContents(True)
        self.original_source_label.setObjectName("original_source_label")
        self.verticalLayout_4.addWidget(self.original_source_label)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.original_source_groupbox, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_save_path = QtWidgets.QLabel(self.centralwidget)
        self.label_save_path.setObjectName("label_save_path")
        self.horizontalLayout_2.addWidget(self.label_save_path)
        self.save_path_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.save_path_lineEdit.setObjectName("save_path_lineEdit")
        self.horizontalLayout_2.addWidget(self.save_path_lineEdit)
        self.save_path_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.save_path_pushButton.setFont(font)
        self.save_path_pushButton.setCheckable(False)
        self.save_path_pushButton.setObjectName("save_path_pushButton")
        self.horizontalLayout_2.addWidget(self.save_path_pushButton)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLoader = QtWidgets.QAction(MainWindow)
        self.actionLoader.setObjectName("actionLoader")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lane Lines Finder"))
        self.label_mode.setText(_translate("MainWindow", "Mode:"))
        self.mode_selection_comboBox.setItemText(0, _translate("MainWindow", "Image"))
        self.mode_selection_comboBox.setItemText(1, _translate("MainWindow", "Video"))
        self.mode_selection_comboBox.setItemText(2, _translate("MainWindow", "Webcam"))
        self.label_load_path.setText(_translate("MainWindow", "Load Path:"))
        self.load_path_pushButton.setText(_translate("MainWindow", "Select"))
        self.replacement_result_groupbox.setTitle(_translate("MainWindow", "Lane Lines Detector"))
        self.original_source_groupbox.setTitle(_translate("MainWindow", "Original Source"))
        self.label_save_path.setText(_translate("MainWindow", "Save Path:"))
        self.save_path_pushButton.setText(_translate("MainWindow", "Select"))
        self.actionLoader.setText(_translate("MainWindow", "Load..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
