# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.replacement_result_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replacement_result_groupbox.sizePolicy().hasHeightForWidth())
        self.replacement_result_groupbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.replacement_result_groupbox.setFont(font)
        self.replacement_result_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.replacement_result_groupbox.setObjectName("replacement_result_groupbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.replacement_result_groupbox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.detection_result_label = QtWidgets.QLabel(self.replacement_result_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detection_result_label.sizePolicy().hasHeightForWidth())
        self.detection_result_label.setSizePolicy(sizePolicy)
        self.detection_result_label.setMinimumSize(QtCore.QSize(400, 240))
        self.detection_result_label.setText("")
        self.detection_result_label.setScaledContents(True)
        self.detection_result_label.setObjectName("detection_result_label")
        self.verticalLayout_7.addWidget(self.detection_result_label)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.replacement_result_groupbox, 0, 1, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_10.addWidget(self.pushButton_start, 1, 0, 1, 1)
        self.original_source_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.original_source_groupbox.setFont(font)
        self.original_source_groupbox.setObjectName("original_source_groupbox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.original_source_groupbox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_image = QtWidgets.QRadioButton(self.original_source_groupbox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.radioButton_image.setFont(font)
        self.radioButton_image.setChecked(True)
        self.radioButton_image.setObjectName("radioButton_image")
        self.horizontalLayout_2.addWidget(self.radioButton_image)
        self.radioButton_video = QtWidgets.QRadioButton(self.original_source_groupbox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.radioButton_video.setFont(font)
        self.radioButton_video.setObjectName("radioButton_video")
        self.horizontalLayout_2.addWidget(self.radioButton_video)
        self.radioButton_camera = QtWidgets.QRadioButton(self.original_source_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_camera.sizePolicy().hasHeightForWidth())
        self.radioButton_camera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.radioButton_camera.setFont(font)
        self.radioButton_camera.setObjectName("radioButton_camera")
        self.horizontalLayout_2.addWidget(self.radioButton_camera)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.original_source_label = QtWidgets.QLabel(self.original_source_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_source_label.sizePolicy().hasHeightForWidth())
        self.original_source_label.setSizePolicy(sizePolicy)
        self.original_source_label.setMinimumSize(QtCore.QSize(400, 240))
        self.original_source_label.setText("")
        self.original_source_label.setScaledContents(True)
        self.original_source_label.setObjectName("original_source_label")
        self.verticalLayout_4.addWidget(self.original_source_label)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.original_source_groupbox, 0, 0, 1, 1)
        self.pushButton_pause = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setCheckable(True)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.gridLayout_10.addWidget(self.pushButton_pause, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 23))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoader = QtWidgets.QAction(MainWindow)
        self.actionLoader.setObjectName("actionLoader")
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionLoader)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Post-it Replace"))
        self.replacement_result_groupbox.setTitle(_translate("MainWindow", "Lane Lines Detector"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.original_source_groupbox.setTitle(_translate("MainWindow", "Original Source"))
        self.radioButton_image.setText(_translate("MainWindow", "Image"))
        self.radioButton_video.setText(_translate("MainWindow", "Video"))
        self.radioButton_camera.setText(_translate("MainWindow", "Camera"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.menuMain.setTitle(_translate("MainWindow", "File"))
        self.actionLoader.setText(_translate("MainWindow", "Load..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
